# -*- coding: utf-8 -*-
"""fine-tune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzO0wo_kuBZfJK7lS71EtYy4SkK3Titd
"""

!pip install -q transformers accelerate peft trl==0.12.0 bitsandbytes datasets

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name , torch_dtype = torch.float16 , device_map = "auto")

def ask(question, schema, max_new_tokens=128):
    prompt = f"""Given the database schema:
{schema}

Write a SQL query to answer: {question}"""

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    return response

schema = "Table: employees (id, name, department, salary)"
question = "What is the average salary of employees in the Engineering department?"

print(ask(question, schema))

from datasets import load_dataset

dataset = load_dataset("xlangai/spider")
print(dataset)
print(dataset["train"][0])

dataset = load_dataset("xlangai/spider")
schema_dataset = load_dataset("richardr1126/spider-schema")
schema_lookup = {row["db_id"]: row for row in schema_dataset["train"]}

def format_schema(db_id):
    row = schema_lookup[db_id]
    formatted = f"Schema:\n{row['Schema (values (type))']}"
    if row["Foreign Keys"]:
        formatted += f"\nForeign Keys:\n{row['Foreign Keys']}"
    return formatted

def build_prompt(question, schema_text):
    return f"""Given the database schema:
{schema_text}

Write a SQL query to answer: {question}

Respond with only the SQL query. No explanation, no markdown formatting."""

def format_example(row):
    schema_text = format_schema(row["db_id"])
    prompt = build_prompt(row["question"], schema_text)
    return {
        "messages": [
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": row["query"]}
        ]
    }

# === BUILD TRAINING DATASET ===
formatted_dataset = dataset["train"].map(format_example, remove_columns=dataset["train"].column_names)

print(" Setup complete.")
print(formatted_dataset)
print(formatted_dataset[0])

example = formatted_dataset[0]['messages']
templated = tokenizer.apply_chat_template(example, tokenize=False)
print(templated)

!pip install -U torchao

from peft import LoraConfig , get_peft_model

lora_config = LoraConfig( r = 16,
                         lora_alpha = 32,
                         lora_dropout = 0.05,
                         target_modules = ['q_proj' , 'v_proj'] ,
                         bias = 'none',
                         task_type = "CAUSAL_LM"
                       )
model = get_peft_model(model , lora_config)
model.print_trainable_parameters()

smoke_dataset = formatted_dataset.select(range(300))
print(smoke_dataset)

from trl import SFTTrainer , SFTConfig

training_args = SFTConfig(
    output_dir="./nl2sql-lora-smoke",
    num_train_epochs=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
    max_length=1024,
    fp16=True, # Use fp16 instead of bf16
    bf16=False
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=smoke_dataset,
)

trainer.train()

# Prep eval subset (formatted same way as train)
eval_dataset = dataset["validation"].select(range(200)).map(
    format_example, remove_columns=dataset["validation"].column_names
)

training_args = SFTConfig(
    output_dir="./nl2sql-lora-full",
    num_train_epochs=2,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=2,
    load_best_model_at_end=True,
    report_to="none",
    max_length=1024,
    fp16=True, # Added for Colab T4 compatibility
    bf16=False
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=formatted_dataset,
    eval_dataset=eval_dataset,
)

trainer.train()

import torch
if torch.cuda.is_available():
    device = "cuda"
    print(f"GPU is available: {torch.cuda.get_device_name(0)}")
    model.to(device)
else:
    device = "cpu"
    print("GPU NOT FOUND. Please go to Runtime -> Change runtime type and select T4 GPU.")